/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IMdi:add': typeof import('~icons/mdi/add')['default']
    'IMdi:import': typeof import('~icons/mdi/import')['default']
    'IMdi:sawBlade': typeof import('~icons/mdi/saw-blade')['default']
    'IMdi:trash': typeof import('~icons/mdi/trash')['default']
    'IStreamline:cutSolid': typeof import('~icons/streamline/cut-solid')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
